[package]
name = "miniwm"
version = "0.1.0"
edition = "2021"
authors = ["Djordje Lukic <lukic.djordje@gmail.com>"]

[dependencies]
thiserror = "1.0.38"
x11 = { version = "2.20.1", features = ["xlib", "xinerama"] }
config = { path = "config" }
execute = "0.2.11"
xlib = { path = "xlib" }